# ---------------------------------------------------------------------------
# crossCorrelationAnalysis.py
# Created on: 2013-02-05 19:31:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
tDiff_rst = "C:\\Users\\90000000000\\Documents\\Yosemite\\Final\\tDiff\\tDiff.rst"
Forest_Mask_rst = "C:\\Users\\90000000000\\Documents\\Yosemite\\Final\\tDiff\\Forest Mask.rst"
MEAN = "C:\\Users\\90000000000\\Documents\\yosemite\\Yosemite GIS\\MEAN"
StDEV = "C:\\Users\\90000000000\\Documents\\yosemite\\Yosemite GIS\\StDEV"

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(Forest_Mask_rst, "Value", tDiff_rst, MEAN, "MEAN", "DATA")

# Process: Zonal Statistics (2)
arcpy.gp.ZonalStatistics_sa(Forest_Mask_rst, "Value", Forest_Mask_rst, StDEV, "STD", "DATA")

